"use client"
import Nav from '@/component/nav/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/component/footer/Footer'
import { usePathname } from 'next/navigation'
import UserContextProvider from '@/context/usercontext'
import AuthWrapper from '@/component/authcheck/check'
const inter = Inter({ subsets: ['latin'] })
import Seeion from '@/component/seeion/s';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const excludedPaths = ['/login','/login/complateinfo'];
  const path=usePathname();
  const shouldRenderNavFooter = !excludedPaths.includes(path);
  return (
    <html lang="en">
      <body className={inter.className}>
      <UserContextProvider>
      <Seeion>
        <AuthWrapper>
      {shouldRenderNavFooter && <Nav />}
        <div className="container">
          {children}
          </div>
        {shouldRenderNavFooter && 
        <Footer />}
        </AuthWrapper>
         </Seeion>
        </UserContextProvider>
      </body>
    </html>
  )
}
